[general]
import = [
    "~/.config/alacritty/burzum.toml",
]

[env]
# TERM = "screen-256color"
TERM = "xterm-256color"

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[window]
padding.x = 4
padding.y = 4
opacity = 1.0
blur = false
# opacity = 0.75
# blur = true
dynamic_padding = false

[mouse]
hide_when_typing = true

[font]
size = 12
# normal = { family = "Px437 OlivettiThin 9x14", style = "Regular" }
# normal = { family = "Px437 LE Model D CGA", style = "Regular" }
# normal = { family = "Px437 Nix8810 M16", style = "Regular" }
# normal = { family = "Px437 IBM VGA 8x16", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font Mono", style = "SemiBold" }

[cursor]
style = { shape = "Block" }

[selection]
save_to_clipboard = true

[debug]
render_timer = false
