[general]
import = [
    # "~/.config/alacritty/burzum.toml",
    "~/.config/alacritty/github.toml",
    # "~/.config/alacritty/lackluster.toml",
]

[env]
TERM = "alacritty"
# TERM = "xterm-256color"

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[window]
padding.x = 4
padding.y = 4
opacity = 1.0
blur = false
dynamic_padding = false

[mouse]
hide_when_typing = true

[font]
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
# normal = { family = "Hack Nerd Font", style = "Regular" }
# normal = { family = "Envy Code R", style = "Regular" }
# bold = { family = "Envy Code R", style = "Regular" }
# italic = { family = "Envy Code R", style = "Regular" }
# bold_italic = { family = "Envy Code R", style = "Regular" }
normal = { family = "Cascadia Code NF", style = "Regular" }
bold = { family = "Cascadia Code NF", style = "Regular" }
italic = { family = "Cascadia Code NF", style = "Regular" }
bold_italic = { family = "Cascadia Code NF", style = "Regular" }
size = 13
# offset = { x = 0, y = -2 }

[cursor]
style = { shape = "Block" }

[selection]
save_to_clipboard = true

[debug]
render_timer = false
