[general]
import = [
    "~/.config/alacritty/citruszest.toml",
]

[env]
# TERM = "screen-256color"
TERM = "xterm-256color"

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[window]
padding.x = 8
padding.y = 8
opacity = 1.0
blur = false
# opacity = 0.75
# blur = true
dynamic_padding = false

[mouse]
hide_when_typing = true

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[cursor]
style = { shape = "Block" }

[selection]
save_to_clipboard = true

[debug]
render_timer = false
