# (Github Dark Colorblind) Colors for kitty

background #0a0c10
foreground #ffffff
url_color #ffffff
# background #0d1117
# foreground #c9d1d9
# url_color #c9d1d9

cursor #afffff
cursor_text_color #323232
# cursor_text_color background

# Tabs
active_tab_background #ec8e2c
active_tab_foreground #0d1117
inactive_tab_background #111d2e
inactive_tab_foreground #6e7681

# Windows Border
# active_border_color #58a6ff
active_border_color #0366d6
inactive_border_color #24282e

# normal
color0 #484f58
color1 #ec8e2c
color2 #0366d6
color3 #d29922
color4 #0366d6
color5 #bc8cff
color6 #26cd4d
color7 #b1bac4
# color2 #58a6ff
# color4 #58a6ff
# color6 #39c5cf

# bright
color8  #6e7681
color9  #fdac54
color10 #79c0ff
color11 #e3b341
color12 #79c0ff
color13 #d2a8ff
color14 #56d4dd
color15 #ffffff
