set -g default-terminal "screen-256color" # "${TERM}"
set -ag terminal-overrides ",*:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g mouse on
set-option -g focus-events on
set-option -g allow-passthrough on

# Status
set-option -g status-position top
set -g status-justify absolute-centre
set -g window-status-current-style "fg=blue,bold"
set -g status-interval 5
set -g status-right '#{?client_prefix, - ,}#(timew | awk "/^ *Total/ {print \$NF}") #[bg=green,fg=black,bold]#(timew | awk "/^ *Tracking/ {print \" \" \$NF \" \"}")#[bg=default]'
set -g status-left "#S"
set -g status-style 'bg=#000000'
set -g status-style 'fg=#ffffff'
set -g pane-border-indicators off
set -g pane-border-status off
set -g pane-border-style fg=#0f0f1f
set -g pane-active-border-style fg=#0f0f1f

bind C-p display-popup -E "python3"
bind C-t display-popup
bind r source-file "/home/crab/.config/tmux/tmux.conf"
bind b set -g status
bind G neww -n "git" -S lazygit
bind E show-environment -g
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'

run '~/.config/tmux/.tmux/plugins/tpm/tpm'
