vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.clipboard:append("unnamedplus")
vim.opt.inccommand = "split"
vim.opt.swapfile = false
vim.opt.winborder = "single"
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.cursorline = true
-- vim.opt.scrolloff = 20
vim.opt.wrap = false
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.showmode = false
vim.opt.cmdheight = 1
vim.opt.background = "dark"
vim.opt.termguicolors = true
vim.opt.signcolumn = "auto:1"
vim.opt.mouse = "a"
vim.g.editorconfig = true
vim.opt.hlsearch = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.guicursor = ""
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#323232" })
vim.cmd[[set completeopt+=menuone,noselect,popup]]
