[default_config]
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86/x86-64"

[default_config.opts]
compiler = "gcc"
compile_flags_txt = ["-Wall", "-O2", "-march=tigerlake"]
diagnostics = true
default_diagnostics = false

# compile_flags_txt = [
#     "cc",
#     "-xassembler",
#     "-Wall",
#     "-Wextra",
#     "-pedantic",
#     "-std=c99",
# ]
