---
CompileFlags:
  Add: [-xc, -Wall, -Wextra, -Wno-used-value, -D_DEFAULT_SOURCE]
  Compiler: gcc
  # Add: [-xc++, -Wall, -Wextra, -Wno-used-value]
  # Compiler: g++
# Documentation:
#   CommentFormat: Doxygen
...
